### ISSUE TITLE
Incorrect usage for ParameterizedSuiteBuilder in ParameterizedSuiteBuilder

### ISSUE THREAD

**Issue by agilepoodle** [NitorCreations/CoreComponents#6]
The Javadoc in WrappingParameterizedRunner describes the usage of ParameterizedSuiteBuilder incorrectly. The code of ParameterizedSuiteBuilder does not support the example used in it.

**Comment by xkr47** [comment]
@agilepoodle which way do you want us to go? :)

**Comment by agilepoodle** [comment]
Both fluent approaches seem decent, but the docs should be aligned :)

**Comment by xkr47** [comment]
To not break existing users, javadoc `withDescription()` method was updated to match actual method name `named()`.
